version: '3.8'

services:

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data

  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: kehutanan
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rh-service:
    build:
      context: ./rh-service
      dockerfile: Dockerfile
    container_name: rh-service
    depends_on:
      - postgres
      - redis
      - minio
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/kehutanan
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      # Redis configuration
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      # Default Cache TTL setting (in seconds)
      SPRING_CACHE_REDIS_TIME_TO_LIVE: 3600
      # Minio configuration
      MINIO_ENDPOINT: http://minio:9000
    ports:
      - "8081:8081"

  pepdas-service:
    build:
      context: ./pepdas-service
      dockerfile: Dockerfile
    container_name: pepdas-service
    depends_on:
      - postgres
      - redis
      - minio
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/kehutanan
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      # Redis configuration
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      # Default Cache TTL setting (in seconds)
      SPRING_CACHE_REDIS_TIME_TO_LIVE: 3600
      # Minio configuration
      MINIO_ENDPOINT: http://minio:9000
    ports:
      - "8082:8081"


  superadmin-service:
    build:
      context: ./superadmin-service
      dockerfile: Dockerfile
    container_name: superadmin-service
    depends_on:
      - postgres
      - redis
      - minio
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/kehutanan
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      # Redis configuration
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      # Default Cache TTL setting (in seconds)
      SPRING_CACHE_REDIS_TIME_TO_LIVE: 3600
      # Minio configuration
      MINIO_ENDPOINT: http://minio:9000
    ports:
      - "8083:8081"

  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 30s
      retries: 50

volumes:
  postgres_data:
  minio_data:
  redis_data:
