database:
  url: jdbc:postgresql://localhost:5432/kehutanan
  username: your_username
  password: your_password
  driver-class-name: org.postgresql.Driver

swagger:
  enabled: true
  api-docs:
    path: /v3/api-docs
  ui:
    path: /swagger-ui.html

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/kehutanan
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

  # Redis Configuration
  cache:
    type: redis
    redis:
      time-to-live: 3600  # Cache TTL in seconds (1 hour)
  data:
    redis:
      host: localhost
      port: 6379

      # password: yourpassword  # Uncomment and set if using password

      

      # Cache Configuration
      # Additional cache properties as needed

server:
  port: 8081

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

minio:
  endpoint: http://minio:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket: rhkehutanan